file_format: "1"
id: madtrix
name: Madtrix
type: shield
url: https://keeb.io/products/iris-keyboard-split-ergonomic-keyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - madtrix_left
  - madtrix_right